title: "r00tCoder's CTF Notes"
author: "Kacper Madej"
description: "© 2025 Kacper Madej — Cybersecurity enthusiast | OSCP+ | CCNA | BTL1 | Sec+| Open to work" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "kacpermadej333@gmail.com"
github_username: "Tymon4511"
linkedin_username: "linkedin.com/in/kacper-madej-b7b523319"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
